.PHONY: setup data train test all clean

all: setup data train test

setup:
	pip install -r requirements.txt
	pip install -e .

data:
	python src/etl.py
	python src/features.py

train:
	python src/train.py

test:
	pytest -v tests/

clean:
	if exist "__pycache__" rd /s /q __pycache__
	if exist "src\__pycache__" rd /s /q src\__pycache__
	if exist "tests\__pycache__" rd /s /q tests\__pycache__
	if exist ".pytest_cache" rd /s /q .pytest_cache
	del /q logs\*
